# Generated by Django 3.0.8 on 2020-07-09 14:14

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(default='None', max_length=50)),
                ('last_name', models.CharField(default='None', max_length=50)),
                ('email', models.CharField(default='None', max_length=50)),
                ('uname', models.CharField(default='None', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=50)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('fatp', models.FloatField(default=0)),
                ('goal', models.CharField(choices=[('Build muscle', 'Build muscle'), ('Get lean', 'Get lean'), ('Mantain weight', 'Mantain weight')], default='None', max_length=50)),
                ('lifestyle', models.CharField(choices=[('Sitting life', 'Sitting life'), ('Standing all day', 'Standing all day'), ('Mover arround constantly', 'Mover arround constantly')], default='None', max_length=50)),
                ('low_cardio', models.IntegerField(default=0)),
                ('high_cardio', models.IntegerField(default=0)),
                ('resistance', models.IntegerField(default=0)),
                ('stretching', models.IntegerField(default=0)),
                ('sleeph', models.FloatField(default=0)),
                ('trackcal', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
