# Generated by Django 3.0.8 on 2020-07-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='None', max_length=50)),
                ('last_name', models.CharField(default='None', max_length=50)),
                ('email', models.CharField(default='None', max_length=50)),
                ('uname', models.CharField(default='None', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=50)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('fatp', models.FloatField(default=0)),
                ('goal', models.CharField(choices=[('Build muscle', 'Build muscle'), ('Get lean', 'Get lean'), ('Mantain weight', 'Mantain weight')], default='None', max_length=50)),
                ('lifestyle', models.CharField(choices=[('Sitting life', 'Sitting life'), ('Standing all day', 'Standing all day'), ('Mover arround constantly', 'Mover arround constantly')], default='None', max_length=50)),
                ('low_cardio', models.IntegerField(default=0)),
                ('high_cardio', models.IntegerField(default=0)),
                ('resistance', models.IntegerField(default=0)),
                ('stretching', models.IntegerField(default=0)),
                ('sleeph', models.FloatField(default=0)),
                ('trackcal', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'userInfo',
                'verbose_name_plural': 'userInfos',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fatp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='high_cardio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lifestyle',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='low_cardio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resistance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sleeph',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stretching',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='trackcal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weight',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
