# Generated by Django 3.0.8 on 2020-07-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200709_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-date_created'], 'verbose_name': 'userInfo', 'verbose_name_plural': 'userInfos'},
        ),
    ]
